# Generated by Django 5.0.9 on 2024-10-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_comment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dean_sign',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Cancelled'), (2, 'Accepted')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='department_head_sign',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Cancelled'), (2, 'Accepted')], default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='study_head_sign',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Cancelled'), (2, 'Accepted')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='study_prorector_sign',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Cancelled'), (2, 'Accepted')]),
        ),
    ]
