# Generated by Django 5.0.9 on 2024-10-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_document_overall_alter_document_dean_sign_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
