# Generated by Django 5.0.9 on 2024-10-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_document_dean_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dean_sign',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Cancelled'), (2, 'Accepted')], default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='study_head_sign',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Cancelled'), (2, 'Accepted')], default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='study_prorector_sign',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Cancelled'), (2, 'Accepted')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Department Head', 'Department Head'), ('Dekan', 'Dekan'), ('Study Head', 'Study Head'), ('Study Prorektor', 'Study Prorektor')], max_length=20),
        ),
    ]
