# Generated by Django 5.0.9 on 2024-10-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_document_dean_sign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dean_sign',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Rad etildi', 'Rad etildi'), ('Qabul qilindi', 'Qabul qilindi')], default='Kutilmoqda', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='department_head_sign',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Rad etildi', 'Rad etildi'), ('Qabul qilindi', 'Qabul qilindi')], default='Kutilmoqda', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='study_head_sign',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Rad etildi', 'Rad etildi'), ('Qabul qilindi', 'Qabul qilindi')], default='Kutilmoqda', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='study_prorector_sign',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Rad etildi', 'Rad etildi'), ('Qabul qilindi', 'Qabul qilindi')], default='Kutilmoqda', max_length=30),
        ),
    ]
