# Generated by Django 5.0.9 on 2024-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_document_options_alter_document_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('accepted', 'Accepted')], default='accepted', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='dean_sign',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('no process', 'No Process')], default='no process', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='department_head_sign',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('no process', 'No Process')], default='no process', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='overall',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('no process', 'No Process')], default='no process', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='study_head_sign',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('no process', 'No Process')], default='no process', max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='study_prorector_sign',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cancelled', 'Cancelled'), ('accepted', 'Accepted'), ('no process', 'No Process')], default='no process', max_length=30),
        ),
    ]
